### ISSUE TITLE
Support Scala 2.13

### ISSUE THREAD

**Issue by cxb811201** [scredis/scredis#62]

**Comment by kpbochenek** [comment]
I have created a branch called `scala2.13` with all dependencies needed for 2.13.
Because of new collections changes in code are required.

It is not blocking support for 2.13 because `scalameter` is only used for testing but still not released for 2.13 and it would be good to see performance difference:
https://github.com/scalameter/scalameter/issues/213

**Comment by kpbochenek** [comment]
Released in `2.2.6`, it still populates to maven central, but should be available in ~1 day, already available in bintray.
